name: build-executables

on:
  push:
    branches:
      # - "main"
      - "devel"
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:

  build-executables-win-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/upload-artifact@v3

    - name: 'build elf'
      run: |
        cargo build --release
        chmod +x ./target/release/fbpconvert

    - name: 'build exe'
      run: |
        cargo build --release --target x86_64-pc-windows-gnu
        chmod +x ./target/x86_64-pc-windows-gnu/release/fbpconvert

    - name: 'upload elf'
      uses: actions/upload-artifact@v3
      with:
        name: fbpconvert
        path: ./target/release/fbpconvert

    - name: 'upload exe'
      uses: actions/upload-artifact@v3
      with:
        name: fbpconvert.exe
        path: ./target/x86_64-pc-windows-gnu/release/fbpconvert

